FROM cwaffles/openpose
# upgrade env
RUN apt update
RUN apt upgrade -y

# install python3 and pip
RUN apt install python3 -y
RUN apt install python3-pip -y
RUN apt install python3-dev -y
RUN apt install python3-setuptools -y
RUN pip3 install --upgrade pip

#Zain: For FFMPEG
RUN apt-get update
RUN apt-get install software-properties-common -y
RUN add-apt-repository ppa:jonathonf/ffmpeg-4 -y
RUN apt-get install ffmpeg -y

# for aiortc
# https://github.com/aiortc/aiortc#requirements
RUN apt install libavdevice-dev -y
RUN apt install libavfilter-dev -y
RUN apt install libopus-dev -y
RUN apt install libvpx-dev -y
RUN apt install pkg-config -y
# not listed but needed...
RUN apt install libopencv-dev -y

#Zain: extra dependencies
RUN pip3 install matplotlib boto3 websockets pillow

# for example app
# https://github.com/aiortc/aiortc/tree/master/examples/server#running
RUN pip install aiortc
RUN pip install aiohttp
RUN pip install opencv-python


