docker exec $1 bash -c "pip3 install boto3"
docker exec $1 bash -c "apt-get update"
docker exec $1 bash -c "apt-get install -y software-properties-common"
docker exec $1 bash -c "add-apt-repository ppa:jonathonf/ffmpeg-4"
docker exec $1 bash -c "apt-get update"
docker exec $1 bash -c "apt-get install -y ffmpeg"
docker exec $1 bash -c "apt-get install -y python-dev pkg-config"
docker exec $1 bash -c "apt install -y libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config"
docker exec $1 bash -c "apt install -y libsrtp2-dev"
docker exec $1 bash -c "pip3 install aiortc websockets"
